<a href="https://colab.research.google.com/github/mindchu/01276551-INTRO-TO-DATA-ANALYTICS/blob/main/Pandas_CH_03_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analytics Book : CODE

**ISBN** : 978-616-338-169-9

**Author** : Rathachai Chawuthai

**Year** : 2022

**Copyright** © by KMITL

**Link** : https://github.com/Rathachai/DA-LAB



---



## **Chapter 3 : Data Processing**


---


### Numpy

In [1]:
[1, 2, 3] + [10, 10, 10]

[1, 2, 3, 10, 10, 10]

In [2]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
a = np.array([1,2,3])

In [6]:
b = np.array([10,20,30])

In [7]:
a+b

array([11, 22, 33])

In [8]:
a*3

array([3, 6, 9])

In [9]:
my_array = np.array([1,2,3,4])

In [10]:
np.sqrt(my_array)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [11]:
np.sum(my_array)

np.int64(10)

In [12]:
np.mean(my_array)

np.float64(2.5)

In [13]:
np.std(my_array)

np.float64(1.118033988749895)

In [14]:
np.min(my_array)

np.int64(1)

In [15]:
np.max(my_array)

np.int64(4)

In [16]:
np.median(my_array)

np.float64(2.5)



---



## **Pandas**

In [17]:
import pandas as pd

## Read CSV

In [18]:
CSV_PATH = "https://rathachai.github.io/DA-LAB/datasets/simple-employee-db.csv"

In [19]:
df = pd.read_csv(CSV_PATH)

In [20]:
df

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.0,4,Bangkok
1,E012,Bordin,male,developer,25,48700.0,2,Phuket
2,E013,Chantana,female,developer,29,45500.0,3,Chonburi
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi
5,E016,Fundee,female,support,35,56600.0,3,Phuket
6,E017,Gitiwit,male,support,26,42400.0,2,Suphanburi
7,E018,Harit,male,devops,32,67700.0,5,Bangkok


## Select Columns and Rows

In [21]:
df['name']

,name
0,Anda
1,Bordin
2,Chantana
3,Donlaya
4,Ekkasit
5,Fundee
6,Gitiwit
7,Harit


In [22]:
df[["name"]]

,name
0,Anda
1,Bordin
2,Chantana
3,Donlaya
4,Ekkasit
5,Fundee
6,Gitiwit
7,Harit


In [23]:
df[["name", "gender", "age"]]

,name,gender,age
0,Anda,female,39
1,Bordin,male,25
2,Chantana,female,29
3,Donlaya,female,39
4,Ekkasit,male,37
5,Fundee,female,35
6,Gitiwit,male,26
7,Harit,male,32


In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
type(df['name'])

pandas.core.series.Series

In [26]:
type(df[['name']])

pandas.core.frame.DataFrame

In [27]:
df.loc[1]

,1
eid,E012
name,Bordin
gender,male
department,developer
age,25
salary,48700.0
working_years,2
birth_place,Phuket


In [28]:
df.loc[[1]]

,eid,name,gender,department,age,salary,working_years,birth_place
1,E012,Bordin,male,developer,25,48700.0,2,Phuket


In [29]:
df.loc[[1,2,3]]

,eid,name,gender,department,age,salary,working_years,birth_place
1,E012,Bordin,male,developer,25,48700.0,2,Phuket
2,E013,Chantana,female,developer,29,45500.0,3,Chonburi
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi


In [30]:
df[["name", "age"]].loc[[1,2,3]]

,name,age
1,Bordin,25
2,Chantana,29
3,Donlaya,39


In [31]:
df.loc[[1,2,3]][["name", "age"]]

,name,age
1,Bordin,25
2,Chantana,29
3,Donlaya,39


In [32]:
df.loc[ [1,2,3] , ['name', 'age'] ]

,name,age
1,Bordin,25
2,Chantana,29
3,Donlaya,39


## Conditional Selections

In [33]:
df['working_years']

,working_years
0,4
1,2
2,3
3,8
4,7
5,3
6,2
7,5


In [34]:
df['working_years']>3

,working_years
0,True
1,False
2,False
3,True
4,True
5,False
6,False
7,True


In [35]:
df[ df['working_years']>3 ]

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.0,4,Bangkok
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi
7,E018,Harit,male,devops,32,67700.0,5,Bangkok


In [36]:
df[ (df["working_years"]>3) & (df["salary"]>70000) ]

,eid,name,gender,department,age,salary,working_years,birth_place
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi


In [37]:
df[ (df["working_years"]>3) & (df["salary"]>70000) & (df["gender"]=='female') ]

,eid,name,gender,department,age,salary,working_years,birth_place
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi


## Edit Values

In [38]:
df

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.0,4,Bangkok
1,E012,Bordin,male,developer,25,48700.0,2,Phuket
2,E013,Chantana,female,developer,29,45500.0,3,Chonburi
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi
5,E016,Fundee,female,support,35,56600.0,3,Phuket
6,E017,Gitiwit,male,support,26,42400.0,2,Suphanburi
7,E018,Harit,male,devops,32,67700.0,5,Bangkok


In [39]:
df.loc[0,"working_years"]

np.int64(4)

In [40]:
df.loc[0,"working_years"] = 77

In [41]:
df

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.0,77,Bangkok
1,E012,Bordin,male,developer,25,48700.0,2,Phuket
2,E013,Chantana,female,developer,29,45500.0,3,Chonburi
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi
5,E016,Fundee,female,support,35,56600.0,3,Phuket
6,E017,Gitiwit,male,support,26,42400.0,2,Suphanburi
7,E018,Harit,male,devops,32,67700.0,5,Bangkok


In [42]:
#stupid way
df.loc[0,"working_years"] = 770
df.loc[1,"working_years"] = 20
df.loc[2,"working_years"] = 30
df.loc[3,"working_years"] = 80
df.loc[4,"working_years"] = 70
df.loc[5,"working_years"] = 30
df.loc[6,"working_years"] = 20
df.loc[7,"working_years"] = 50

In [43]:
#smarter way
for i in range(8):
  df.loc[i,"working_years"] = df.loc[i,"working_years"]*10

In [44]:
#smartest way
df["working_years"] = df["working_years"]*10

In [45]:
df

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.0,77000,Bangkok
1,E012,Bordin,male,developer,25,48700.0,2000,Phuket
2,E013,Chantana,female,developer,29,45500.0,3000,Chonburi
3,E014,Donlaya,female,marketing,39,72600.0,8000,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7000,Suphanburi
5,E016,Fundee,female,support,35,56600.0,3000,Phuket
6,E017,Gitiwit,male,support,26,42400.0,2000,Suphanburi
7,E018,Harit,male,devops,32,67700.0,5000,Bangkok


## Set Index

In [46]:
df.set_index("eid", inplace=True)

In [47]:
df

,name,gender,department,age,salary,working_years,birth_place
eid,,,,,,,
E011,Anda,female,developer,39,64200.0,77000,Bangkok
E012,Bordin,male,developer,25,48700.0,2000,Phuket
E013,Chantana,female,developer,29,45500.0,3000,Chonburi
E014,Donlaya,female,marketing,39,72600.0,8000,Chonburi
E015,Ekkasit,male,marketing,37,80500.0,7000,Suphanburi
E016,Fundee,female,support,35,56600.0,3000,Phuket
E017,Gitiwit,male,support,26,42400.0,2000,Suphanburi
E018,Harit,male,devops,32,67700.0,5000,Bangkok


In [48]:
df.loc['E011']

,E011
name,Anda
gender,female
department,developer
age,39
salary,64200.0
working_years,77000
birth_place,Bangkok


In [49]:
df.reset_index(inplace=True)

In [50]:
df

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.0,77000,Bangkok
1,E012,Bordin,male,developer,25,48700.0,2000,Phuket
2,E013,Chantana,female,developer,29,45500.0,3000,Chonburi
3,E014,Donlaya,female,marketing,39,72600.0,8000,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7000,Suphanburi
5,E016,Fundee,female,support,35,56600.0,3000,Phuket
6,E017,Gitiwit,male,support,26,42400.0,2000,Suphanburi
7,E018,Harit,male,devops,32,67700.0,5000,Bangkok


## Working with Columns

In [51]:
df['salary']

,salary
0,64200.0
1,48700.0
2,45500.0
3,72600.0
4,80500.0
5,56600.0
6,42400.0
7,67700.0


In [52]:
df["salary"]*12

,salary
0,770400.0
1,584400.0
2,546000.0
3,871200.0
4,966000.0
5,679200.0
6,508800.0
7,812400.0


In [53]:
df["salary"]*df["working_years"]

,0
0,4.943400e+09
1,9.740000e+07
2,1.365000e+08
3,5.808000e+08
4,5.635000e+08
5,1.698000e+08
6,8.480000e+07
7,3.385000e+08


In [54]:
df["salary"].sum()

np.float64(478200.0)

In [55]:
df['salary'].max()

80500.0

In [56]:
df['salary'].min()

42400.0

In [57]:
df['salary'].mean()

np.float64(59775.0)

In [58]:
df['salary'].std()

13705.03035906368

In [59]:
np.sqrt(df['salary'])

,salary
0,253.377189
1,220.680765
2,213.307290
3,269.443872
4,283.725219
5,237.907545
6,205.912603
7,260.192237


In [60]:
df["salary"].apply(np.sqrt)

,salary
0,253.377189
1,220.680765
2,213.307290
3,269.443872
4,283.725219
5,237.907545
6,205.912603
7,260.192237


## Working with Funcion

In [61]:
def salary_type(salary):
  if salary>50000:
    return 'high'
  else:
    return 'enough'

In [62]:
df["salary"].apply(salary_type)

,salary
0,high
1,enough
2,enough
3,high
4,high
5,high
6,enough
7,high


In [63]:
df["salary"].apply(lambda x: salary_type(x))

,salary
0,high
1,enough
2,enough
3,high
4,high
5,high
6,enough
7,high


In [64]:
df["salary"].apply(lambda x: "high" if x>50000 else "enough")

,salary
0,high
1,enough
2,enough
3,high
4,high
5,high
6,enough
7,high


## Read every Row

In [65]:
for index, row in df.iterrows():
  print(index)

0
1
2
3
4
5
6
7


In [66]:
for index, row in df.iterrows():
  print(row['name'])

Anda
Bordin
Chantana
Donlaya
Ekkasit
Fundee
Gitiwit
Harit


In [67]:
for index, row in df.iterrows():
  name = row['name']
  age = row['age']
  salary = row['salary']
  print(name, age, salary)

Anda 39 64200.0
Bordin 25 48700.0
Chantana 29 45500.0
Donlaya 39 72600.0
Ekkasit 37 80500.0
Fundee 35 56600.0
Gitiwit 26 42400.0
Harit 32 67700.0


In [68]:
for index, row in df.iterrows():
  name = row['name']
  age = row['age']
  salary = row['salary']
  if age>35:
    df.loc[index, 'salary'] = salary + 0.99

In [69]:
df

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.99,77000,Bangkok
1,E012,Bordin,male,developer,25,48700.00,2000,Phuket
2,E013,Chantana,female,developer,29,45500.00,3000,Chonburi
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi
5,E016,Fundee,female,support,35,56600.00,3000,Phuket
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok


## New Column

In [70]:
df

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.99,77000,Bangkok
1,E012,Bordin,male,developer,25,48700.00,2000,Phuket
2,E013,Chantana,female,developer,29,45500.00,3000,Chonburi
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi
5,E016,Fundee,female,support,35,56600.00,3000,Phuket
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok


In [71]:
df["country"] = "Thailand"

In [72]:
df

,eid,name,gender,department,age,salary,working_years,birth_place,country
0,E011,Anda,female,developer,39,64200.99,77000,Bangkok,Thailand
1,E012,Bordin,male,developer,25,48700.00,2000,Phuket,Thailand
2,E013,Chantana,female,developer,29,45500.00,3000,Chonburi,Thailand
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi,Thailand
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi,Thailand
5,E016,Fundee,female,support,35,56600.00,3000,Phuket,Thailand
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi,Thailand
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok,Thailand


In [73]:
df["bonus"] = df["salary"]*df["working_years"]

In [74]:
df

,eid,name,gender,department,age,salary,working_years,birth_place,country,bonus
0,E011,Anda,female,developer,39,64200.99,77000,Bangkok,Thailand,4.943476e+09
1,E012,Bordin,male,developer,25,48700.00,2000,Phuket,Thailand,9.740000e+07
2,E013,Chantana,female,developer,29,45500.00,3000,Chonburi,Thailand,1.365000e+08
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi,Thailand,5.808079e+08
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi,Thailand,5.635069e+08
5,E016,Fundee,female,support,35,56600.00,3000,Phuket,Thailand,1.698000e+08
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi,Thailand,8.480000e+07
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok,Thailand,3.385000e+08


In [75]:
df['birth_year']=2025-df['age']

In [76]:
df

,eid,name,gender,department,age,salary,working_years,birth_place,country,bonus,birth_year
0,E011,Anda,female,developer,39,64200.99,77000,Bangkok,Thailand,4.943476e+09,1986
1,E012,Bordin,male,developer,25,48700.00,2000,Phuket,Thailand,9.740000e+07,2000
2,E013,Chantana,female,developer,29,45500.00,3000,Chonburi,Thailand,1.365000e+08,1996
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi,Thailand,5.808079e+08,1986
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi,Thailand,5.635069e+08,1988
5,E016,Fundee,female,support,35,56600.00,3000,Phuket,Thailand,1.698000e+08,1990
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi,Thailand,8.480000e+07,1999
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok,Thailand,3.385000e+08,1993


## Drop Data

In [77]:
df

,eid,name,gender,department,age,salary,working_years,birth_place,country,bonus,birth_year
0,E011,Anda,female,developer,39,64200.99,77000,Bangkok,Thailand,4.943476e+09,1986
1,E012,Bordin,male,developer,25,48700.00,2000,Phuket,Thailand,9.740000e+07,2000
2,E013,Chantana,female,developer,29,45500.00,3000,Chonburi,Thailand,1.365000e+08,1996
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi,Thailand,5.808079e+08,1986
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi,Thailand,5.635069e+08,1988
5,E016,Fundee,female,support,35,56600.00,3000,Phuket,Thailand,1.698000e+08,1990
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi,Thailand,8.480000e+07,1999
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok,Thailand,3.385000e+08,1993


In [78]:
df.drop([0,1,2])

,eid,name,gender,department,age,salary,working_years,birth_place,country,bonus,birth_year
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi,Thailand,580807920.0,1986
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi,Thailand,563506930.0,1988
5,E016,Fundee,female,support,35,56600.00,3000,Phuket,Thailand,169800000.0,1990
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi,Thailand,84800000.0,1999
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok,Thailand,338500000.0,1993


In [79]:
df

,eid,name,gender,department,age,salary,working_years,birth_place,country,bonus,birth_year
0,E011,Anda,female,developer,39,64200.99,77000,Bangkok,Thailand,4.943476e+09,1986
1,E012,Bordin,male,developer,25,48700.00,2000,Phuket,Thailand,9.740000e+07,2000
2,E013,Chantana,female,developer,29,45500.00,3000,Chonburi,Thailand,1.365000e+08,1996
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi,Thailand,5.808079e+08,1986
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi,Thailand,5.635069e+08,1988
5,E016,Fundee,female,support,35,56600.00,3000,Phuket,Thailand,1.698000e+08,1990
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi,Thailand,8.480000e+07,1999
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok,Thailand,3.385000e+08,1993


In [80]:
df.drop([0,1,2] , inplace=True)

In [81]:
df

,eid,name,gender,department,age,salary,working_years,birth_place,country,bonus,birth_year
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi,Thailand,580807920.0,1986
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi,Thailand,563506930.0,1988
5,E016,Fundee,female,support,35,56600.00,3000,Phuket,Thailand,169800000.0,1990
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi,Thailand,84800000.0,1999
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok,Thailand,338500000.0,1993


In [82]:
df.drop(["country","bonus"], axis=1, inplace=True)

In [83]:
df

,eid,name,gender,department,age,salary,working_years,birth_place,birth_year
3,E014,Donlaya,female,marketing,39,72600.99,8000,Chonburi,1986
4,E015,Ekkasit,male,marketing,37,80500.99,7000,Suphanburi,1988
5,E016,Fundee,female,support,35,56600.00,3000,Phuket,1990
6,E017,Gitiwit,male,support,26,42400.00,2000,Suphanburi,1999
7,E018,Harit,male,devops,32,67700.00,5000,Bangkok,1993


## Reload Data

In [84]:
df = pd.read_csv(CSV_PATH)

In [85]:
df

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.0,4,Bangkok
1,E012,Bordin,male,developer,25,48700.0,2,Phuket
2,E013,Chantana,female,developer,29,45500.0,3,Chonburi
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi
5,E016,Fundee,female,support,35,56600.0,3,Phuket
6,E017,Gitiwit,male,support,26,42400.0,2,Suphanburi
7,E018,Harit,male,devops,32,67700.0,5,Bangkok


## Sort

In [86]:
df.sort_values("salary")

,eid,name,gender,department,age,salary,working_years,birth_place
6,E017,Gitiwit,male,support,26,42400.0,2,Suphanburi
2,E013,Chantana,female,developer,29,45500.0,3,Chonburi
1,E012,Bordin,male,developer,25,48700.0,2,Phuket
5,E016,Fundee,female,support,35,56600.0,3,Phuket
0,E011,Anda,female,developer,39,64200.0,4,Bangkok
7,E018,Harit,male,devops,32,67700.0,5,Bangkok
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi


In [87]:
df.sort_values("salary", ascending=False)

,eid,name,gender,department,age,salary,working_years,birth_place
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
7,E018,Harit,male,devops,32,67700.0,5,Bangkok
0,E011,Anda,female,developer,39,64200.0,4,Bangkok
5,E016,Fundee,female,support,35,56600.0,3,Phuket
1,E012,Bordin,male,developer,25,48700.0,2,Phuket
2,E013,Chantana,female,developer,29,45500.0,3,Chonburi
6,E017,Gitiwit,male,support,26,42400.0,2,Suphanburi


In [88]:
df.sort_values(['gender', 'salary'])

,eid,name,gender,department,age,salary,working_years,birth_place
2,E013,Chantana,female,developer,29,45500.0,3,Chonburi
5,E016,Fundee,female,support,35,56600.0,3,Phuket
0,E011,Anda,female,developer,39,64200.0,4,Bangkok
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
6,E017,Gitiwit,male,support,26,42400.0,2,Suphanburi
1,E012,Bordin,male,developer,25,48700.0,2,Phuket
7,E018,Harit,male,devops,32,67700.0,5,Bangkok
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi


## Group By

In [89]:
df

,eid,name,gender,department,age,salary,working_years,birth_place
0,E011,Anda,female,developer,39,64200.0,4,Bangkok
1,E012,Bordin,male,developer,25,48700.0,2,Phuket
2,E013,Chantana,female,developer,29,45500.0,3,Chonburi
3,E014,Donlaya,female,marketing,39,72600.0,8,Chonburi
4,E015,Ekkasit,male,marketing,37,80500.0,7,Suphanburi
5,E016,Fundee,female,support,35,56600.0,3,Phuket
6,E017,Gitiwit,male,support,26,42400.0,2,Suphanburi
7,E018,Harit,male,devops,32,67700.0,5,Bangkok


In [90]:
df.groupby("department")[['salary', 'age']].mean()

,salary,age
department,,
developer,52800.0,31.0
devops,67700.0,32.0
marketing,76550.0,38.0
support,49500.0,30.5


In [91]:
df.groupby(["department","gender"])[['salary', 'age']].mean()

salary   age
department gender               
developer  female  54850.0  34.0
           male    48700.0  25.0
devops     male    67700.0  32.0
marketing  female  72600.0  39.0
           male    80500.0  37.0
support    female  56600.0  35.0
           male    42400.0  26.0

In [92]:
df.groupby("department")[['salary', 'age']].agg(["mean", "count"])

salary         age      
               mean count  mean count
department                           
developer   52800.0     3  31.0     3
devops      67700.0     1  32.0     1
marketing   76550.0     2  38.0     2
support     49500.0     2  30.5     2

In [93]:
df.groupby("department").agg({"age":["min","max"], "salary":"mean"})

age       salary
           min max     mean
department                 
developer   25  39  52800.0
devops      32  32  67700.0
marketing   37  39  76550.0
support     26  35  49500.0

## Save to CSV

In [94]:
df.to_csv("employee.csv")

In [95]:
df.to_csv("employee.csv", index=False)

In [96]:
df.to_csv("employee.csv", index=False, encoding='utf-8-sig')



---



https://rathachai.creatier.pro/